Refactoring.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -1,7 +1,7 @@
 #!/bin/bash
 # imos is a utility library for BASH.
 
-IMOSH_VERSION='2014-10-06 02:12:55 +0900 (20b1158)'
+IMOSH_VERSION='2014-10-06 03:01:10 +0900 (da84211)'
 
 # Enables error checking if imosh is called in a script.
 if ! shopt login_shell >/dev/null; then
@@ -192,11 +192,11 @@ __func::quick_sort() {
   fi
 }
 
-# func::fgets -- Gets a line from STDIN.
+# fgets -- Gets a line from STDIN.
 #
 # fgets reads a line and regards it as a result.  fgets does not strip a
-# trailing new line.  Function form sets the result to the variable.  Subroutine
-# form outputs the result to STDOUT.
+# trailing new line.  The function form sets the result to a variable.  The
+# subroutine form outputs the result to the standard output.
 #
 # Usage:
 #     // 1. Function form.
@@ -204,32 +204,42 @@ __func::quick_sort() {
 #     // 2. Subroutine form.
 #     bool sub::fgets() > line
 func::fgets() {
-  local __fgets_variable="$1"
-  local __fgets_buffer=''
-  local __fgets_line=''
+  if [ "$#" -eq 1 ]; then
+    local __fgets_variable="$1"
+    local __fgets_buffer=''
+    local __fgets_line=''
 
-  func::let "${__fgets_variable}" ''
-  if ! IFS= read -r -n 1 -d '' __fgets_buffer; then
+    func::let "${__fgets_variable}" ''
+    if ! IFS= read -r -n 1 -d '' __fgets_buffer; then
+      return 1
+    fi
+    __fgets_line+="${__fgets_buffer}"
+    if [ "${__fgets_buffer}" = $'\n' ]; then
+      func::strcpy "${__fgets_variable}" __fgets_buffer
+      return
+    fi
+    if IFS= read -r -d $'\n' __fgets_buffer; then
+      __fgets_buffer+=$'\n'
+    fi
+    __fgets_line+="${__fgets_buffer}"
+    func::strcpy "${__fgets_variable}" __fgets_line
+  else
+    LOG ERROR "Wrong number of arguments: $#"
     return 1
   fi
-  __fgets_line+="${__fgets_buffer}"
-  if [ "${__fgets_buffer}" = $'\n' ]; then
-    func::strcpy "${__fgets_variable}" __fgets_buffer
-    return
-  fi
-  if IFS= read -r -d $'\n' __fgets_buffer; then
-    __fgets_buffer+=$'\n'
-  fi
-  __fgets_line+="${__fgets_buffer}"
-  func::strcpy "${__fgets_variable}" __fgets_line
 }
 
 sub::fgets() {
-  local variable=''
-  if ! func::fgets variable; then
+  if [ "$#" -eq 0 ]; then
+    local variable=''
+    if ! func::fgets variable; then
+      return 1
+    fi
+    func::print "${variable}"
+  else
+    LOG ERROR "Wrong number of arguments: $#"
     return 1
   fi
-  func::print "${variable}"
 }
 
 # file_get_contents -- Reads an entire file into a string.
@@ -299,17 +309,22 @@ stream::file_get_contents() {
 # Usage:
 #     void func::readarray() < input
 func::readarray() {
-  local line=''
-  NEWLINE=''
-  LINE=''
-  if ! func::readline; then
-    LINE=()
+  if [ "$#" -eq 0 ]; then
+    local line=''
+    NEWLINE=''
+    LINE=''
+    if ! func::readline; then
+      LINE=()
+      return 1
+    fi
+    local ifs="${IFS}"
+    ifs="${ifs//'['/\[}"
+    ifs="${ifs//']'/\]}"
+    func::greg_split LINE "[${ifs}]" "${LINE}"
+  else
+    LOG ERROR "Wrong number of arguments: $#"
     return 1
   fi
-  local ifs="${IFS}"
-  ifs="${ifs//'['/\[}"
-  ifs="${ifs//']'/\]}"
-  func::greg_split LINE "[${ifs}]" "${LINE}"
 }
 
 # readline -- Gets a line.
@@ -320,27 +335,32 @@ func::readarray() {
 # Usage:
 #     void func::readline() < input
 func::readline() {
-  local line=''
-  NEWLINE=''
-  LINE=''
-  if ! func::fgets line; then
-    return 1
-  fi
-  if [ "${line:$((${#line} - 2))}" = $'\r\n' ]; then
-    NEWLINE=$'\r\n'
-    LINE="${line%$'\r\n'}"
-  elif [ "${line:$((${#line} - 1))}" = $'\n' ]; then
-    NEWLINE=$'\n'
-    LINE="${line%$'\n'}"
-  else
+  if [ "$#" -eq 0 ]; then
+    local line=''
     NEWLINE=''
-    LINE="${line}"
+    LINE=''
+    if ! func::fgets line; then
+      return 1
+    fi
+    if [ "${line:$((${#line} - 2))}" = $'\r\n' ]; then
+      NEWLINE=$'\r\n'
+      LINE="${line%$'\r\n'}"
+    elif [ "${line:$((${#line} - 1))}" = $'\n' ]; then
+      NEWLINE=$'\n'
+      LINE="${line%$'\n'}"
+    else
+      NEWLINE=''
+      LINE="${line}"
+    fi
+  else
+    LOG ERROR "Wrong number of arguments: $#"
+    return 1
   fi
 }
 
-# func::tmpfile -- Creates a temporary file.
+# tmpfile -- Creates a temporary file.
 #
-# Creates a temporary file with a unique name under ${TMPDIR}.
+# tmpfile creates a temporary file with a unique name under ${TMPDIR}.
 #
 # Usage:
 #     // 1. Function form.
@@ -1113,6 +1133,12 @@ func::cast() {
   esac
 }
 
+func::cast_or_die() {
+  if ! func::cast "$@"; then
+    IFS=' ' eval 'LOG FATAL "Type mismatch: $*"'
+  fi
+}
+
 # func::floatval -- Casts a variable as a float value.
 #
 # Casts variable into float type.  If it fails, returns 1.
@@ -1195,17 +1221,30 @@ func::strval() {
 }
 
 CHECK() {
-  local __CHECK_invert="$1"
-
-  if [ "${__CHECK_invert}" = '!' ]; then
+  IFS=' ' eval 'local __CHECK_message="Check failure: $*"'
+  if [ "$#" -ge 1 ] && [ "${1:0:10}" = '--message=' ]; then
+    __CHECK_message="${1:10}"
     shift
-    if "$@"; then
-      IFS=' ' eval 'imosh::stack_trace "*** Check failure: ! $* ***"'
+  fi
+
+  if [ "$#" -ge 1 ]; then
+    local __CHECK_invert="$1"
+
+    if [ "${__CHECK_invert}" = '!' ]; then
+      shift
+      if "$@"; then
+        IFS=' ' eval 'LOG ERROR "Check failure: ! $*"'
+        LOG FATAL "${__CHECK_message}"
+      fi
+    else
+      if ! "$@"; then
+        IFS=' ' eval 'LOG ERROR "Check failure: $*"'
+        LOG FATAL "${__CHECK_message}"
+      fi
     fi
   else
-    if ! "$@"; then
-      IFS=' ' eval 'imosh::stack_trace "*** Check failure: $* ***"'
-    fi
+    LOG ERROR "Wrong number of arguments: $#"
+    return 1
   fi
 }
 
@@ -1390,15 +1429,9 @@ imosh::internal::parse_args() {
     arg_value="${arg_value:1}"
     if func::isset "${upper_class_name}S_${arg_name}"; then
       if [ "${class_name}" = 'flag' ]; then
-        if ! imosh::internal::convert_type \
-               "$(imosh::internal::flag_type "${arg_name}")" \
-               "${arg_value}" >/dev/null; then
-          LOG FATAL "the ${arg_name} flag has an invalid value: ${arg_value}"
-        else
-          arg_value="$(imosh::internal::convert_type \
-                             "$(imosh::internal::flag_type "${arg_name}")" \
-                             "${arg_value}")"
-        fi
+        local original_value="${arg_value}"
+        func::cast_or_die \
+            arg_value "$(imosh::internal::flag_type "${arg_name}")"
       fi
       IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=${arg_value}")
       continue
@@ -1511,11 +1544,9 @@ imosh::internal::define_flag() {
   if func::isset "IMOSH_FLAGS_${name}"; then
     func::strcpy default_value "IMOSH_FLAGS_${name}"
   fi
-  if ! imosh::internal::convert_type \
-           "${type}" "${default_value}" >/dev/null; then
-    LOG FATAL "${type}'s default value should be ${type}: ${default_value}"
-  fi
-  default_value="$(imosh::internal::convert_type "${type}" "${default_value}")"
+  CHECK \
+      --message="${name}'s default value is invalid: ${default_value}." \
+      func::cast default_value "${type}"
   if func::isset "__IMOSH_FLAGS_TYPE_${name}"; then
     LOG FATAL "already defined flag: ${name}"
   fi
