Refactoring mktemp.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -2357,17 +2357,6 @@ imosh::stack_trace() {
   done
 }
 
-__imosh::mktemp() {
-  TMPDIR="${TMPDIR:-/tmp}"
-  TMPDIR="${TMPDIR%/}"
-  export TMPDIR="${TMPDIR}/imosh.${RANDOM}.${RANDOM}.${RANDOM}.${RANDOM}"
-  export IMOSH_TMPDIR="${TMPDIR}"
-  export __IMOSH_CORE_TMPDIR="${TMPDIR}/.imosh"
-  if ! mkdir -p "${__IMOSH_CORE_TMPDIR}"; then
-    LOG FATAL "Failed to create a temporary directory: ${__IMOSH_CORE_TMPDIR}"
-  fi
-}
-
 # __imosh::get_usage
 #
 # Usage:
@@ -2773,7 +2762,14 @@ exec 101>/dev/null 102>/dev/null 103>/dev/null 104>/dev/null
 exec 105>&2
 
 # Prepares a temporary directory and sets its path to TMPDIR.
-__imosh::mktemp
+TMPDIR="${TMPDIR:-/tmp}"
+TMPDIR="${TMPDIR%/}"
+export TMPDIR="${TMPDIR}/imosh.${RANDOM}.${RANDOM}.${RANDOM}.${RANDOM}"
+export IMOSH_TMPDIR="${TMPDIR}"
+export __IMOSH_CORE_TMPDIR="${TMPDIR}/.imosh"
+if ! mkdir -p "${__IMOSH_CORE_TMPDIR}"; then
+  LOG FATAL "Failed to create a temporary directory: ${__IMOSH_CORE_TMPDIR}"
+fi
 
 if sub::isset IMOSH_USE_DEFINE_FLAGS && (( IMOSH_USE_DEFINE_FLAGS )); then
   DEFINE_bool --group=imosh --alias=h help false \
