Refactoring.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -3,7 +3,7 @@
 #
 # For more details, see https://github.com/imos/imosh
 
-IMOSH_VERSION='2014-11-16 23:24:55 +0900 (a5f0c20)'
+IMOSH_VERSION='2014-11-16 23:40:34 +0900 (053b614)'
 
 # Enables error checking if imosh is called in a script.
 if ! shopt login_shell >/dev/null; then
@@ -1492,11 +1492,14 @@ func::boolval() {
 # Casts variable into a specified type.
 #
 # Usage:
+#     // 1. Function form.
 #     bool func::cast(variant* variable, string type)
+#     // 2. Function form. (Dies if conversion fails.)
+#     void func::cast_or_die(variant* variable, string type)
 func::cast() {
   if [ "$#" -eq 2 ]; then
     case "${2}" in
-      multi*)
+      'MULTI'*)
         local __cast_values=()
         local __cast_element_type="${2:5}"
         func::array_values __cast_values "${1}"
@@ -1510,11 +1513,11 @@ func::cast() {
         fi
         func::array_values "${1}" __cast_values
         ;;
-      int)     func::intval "${1}" || return "$?";;
-      float)   func::floatval "${1}" || return "$?";;
-      string)  func::strval "${1}" || return "$?";;
-      bool)    func::boolval "${1}" || return "$?";;
-      variant) return 0;;
+      'INT')     func::intval "${1}" || return "$?";;
+      'FLOAT')   func::floatval "${1}" || return "$?";;
+      'STRING')  func::strval "${1}" || return "$?";;
+      'BOOL')    func::boolval "${1}" || return "$?";;
+      'VARIANT') return 0;;
       *)       LOG FATAL "Unknown type: ${2}";;
     esac
   else
@@ -1868,7 +1871,7 @@ imosh::internal::parse_args() {
       if [ "${arg_name:0:2}" = 'no' ]; then
         if sub::isset "${upper_class_name}S_${arg_name:2}"; then
           if [ "${class_name}" != 'flag' ] || \
-             [ "$(imosh::internal::flag_type "${arg_name:2}")" = 'bool' ]; then
+             [ "$(imosh::internal::flag_type "${arg_name:2}")" = 'BOOL' ]; then
             IMOSH_ARGS+=("${upper_class_name}S_${arg_name:2}=0")
             continue
           fi
@@ -1876,7 +1879,7 @@ imosh::internal::parse_args() {
       fi
       if sub::isset "${upper_class_name}S_${arg_name}"; then
         if [ "${class_name}" != 'flag' ] ||
-           [ "$(imosh::internal::flag_type "${arg_name}")" = 'bool' ]; then
+           [ "$(imosh::internal::flag_type "${arg_name}")" = 'BOOL' ]; then
           IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=1")
           continue
         fi
@@ -1896,14 +1899,14 @@ imosh::internal::parse_args() {
       if [ "${class_name}" = 'flag' ]; then
         local original_value="${arg_value}"
         local type="$(imosh::internal::flag_type "${arg_name}")"
-        if [ "${type:0:5}" = 'multi' ]; then
+        if [ "${type:0:5}" = 'MULTI' ]; then
           # TODO(imos): Support delimiter.
           func::explode arg_value ',' "${arg_value}"
         fi
         CHECK \
             --message="${upper_class_name}S_${arg_name} is invalid: ${arg_value}" \
             func::cast arg_value "$(imosh::internal::flag_type "${arg_name}")"
-        if [ "${type:0:5}" = 'multi' ]; then
+        if [ "${type:0:5}" = 'MULTI' ]; then
           # Set values here.  FLAGS_* are global variables, and this does not
           # cause scope issues.
           func::array_values "${upper_class_name}S_${arg_name}" arg_value
@@ -2024,7 +2027,7 @@ imosh::internal::define_flag() {
   if sub::isset "IMOSH_FLAGS_${name}"; then
     func::strcpy default_value "IMOSH_FLAGS_${name}"
   fi
-  if [ "${type:0:5}" = 'multi' ]; then
+  if [ "${type:0:5}" = 'MULTI' ]; then
     func::explode default_value ',' "${default_value}"
   fi
   CHECK \
@@ -2033,7 +2036,7 @@ imosh::internal::define_flag() {
   if sub::isset "__IMOSH_FLAGS_TYPE_${name}"; then
     LOG FATAL "already defined flag: ${name}"
   fi
-  if [ "${type:0:5}" = 'multi' ]; then
+  if [ "${type:0:5}" = 'MULTI' ]; then
     func::array_values "FLAGS_${name}" 'default_value'
   else
     func::strcpy "FLAGS_${name}" 'default_value'
@@ -2047,8 +2050,8 @@ imosh::internal::define_flag() {
   if (( ! ARGS_alias_flag )); then
     local escaped_default_value=''
     case "${type}" in
-      int) escaped_default_value="${default_value}";;
-      bool)
+      'INT') escaped_default_value="${default_value}";;
+      'BOOL')
         if (( default_value )); then
           escaped_default_value='true'
         else
@@ -2070,14 +2073,14 @@ imosh::internal::define_flag() {
   fi
 }
 
-DEFINE_string() { imosh::internal::define_flag string "$@"; }
-DEFINE_int() { imosh::internal::define_flag int "$@"; }
-DEFINE_bool() { imosh::internal::define_flag bool "$@"; }
-DEFINE_double() { imosh::internal::define_flag double "$@"; }
-DEFINE_multistring() { imosh::internal::define_flag multistring "$@"; }
-DEFINE_multiint() { imosh::internal::define_flag multiint "$@"; }
-DEFINE_multibool() { imosh::internal::define_flag multibool "$@"; }
-DEFINE_multidouble() { imosh::internal::define_flag multidouble "$@"; }
+DEFINE_string() { imosh::internal::define_flag STRING "$@"; }
+DEFINE_int() { imosh::internal::define_flag INT "$@"; }
+DEFINE_bool() { imosh::internal::define_flag BOOL "$@"; }
+DEFINE_double() { imosh::internal::define_flag DOUBLE "$@"; }
+DEFINE_multistring() { imosh::internal::define_flag MULTISTRING "$@"; }
+DEFINE_multiint() { imosh::internal::define_flag MULTIINT "$@"; }
+DEFINE_multibool() { imosh::internal::define_flag MULTIBOOL "$@"; }
+DEFINE_multidouble() { imosh::internal::define_flag MULTIDOUBLE "$@"; }
 DEFINE_list() { DEFINE_multistring "$@"; }
 
 imosh::internal::get_main_script() {
