Add get_child_processes.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -9,6 +9,11 @@ print() {
   printf "%s" "$*"
 }
 
+imosh::get_child_processes() {
+  local ppid="$1"
+  ps -axo ppid,pid | awk "{ if (\$1 == ${ppid}) print \$2; }"
+}
+
 imosh::internal::style() {
   echo -en "\\033[${1}m"
 }
@@ -86,9 +91,6 @@ imosh::internal::define_flag() {
   if php::isset "__IMOSH_FLAGS_TYPE_${name}"; then
     LOG FATAL "already defined flag: ${name}"
   fi
-  case "${type}" in
-    int|bool) declare -i "FLAGS_${name}";;
-  esac
   eval "FLAGS_${name}=$(imosh::shell_escape "${default_value}")"
   eval "__IMOSH_FLAGS_TYPE_${name}=${type}"
   eval "__IMOSH_FLAGS_DESCRIPTION_${name}=$(
@@ -375,7 +377,7 @@ imosh::internal::parse_args() {
       if [ "${arg_name:0:2}" == 'no' ]; then
         if php::isset "${upper_class_name}S_${arg_name:2}"; then
           if [ "${class_name}" == 'flag' ] && \
-             [ "$(imosh::internal::flag_type "${arg_name:2}")" != 'bool']; then
+             [ "$(imosh::internal::flag_type "${arg_name:2}")" != 'bool' ]; then
             LOG FATAL "the ${arg_name:2} flag is not a bool flag"
           fi
           IMOSH_ARGS+=("${upper_class_name}S_${arg_name:2}=0")
@@ -384,7 +386,7 @@ imosh::internal::parse_args() {
       fi
       if php::isset "${upper_class_name}S_${arg_name}"; then
         if [ "${class_name}" == 'flag' ] && \
-           [ "$(imosh::internal::flag_type "${arg_name}")" != 'bool']; then
+           [ "$(imosh::internal::flag_type "${arg_name}")" != 'bool' ]; then
           LOG FATAL "the ${arg_name} flag is not a bool flag"
         fi
         IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=1")
@@ -393,14 +395,20 @@ imosh::internal::parse_args() {
       LOG FATAL "no such bool ${class_name} is defined:" \
                 "(${upper_class_name}S_)${arg_name}"
     fi
+    arg_value="${arg_value:1}"
     if php::isset "${upper_class_name}S_${arg_name}"; then
-      if [ "${class_name}" == 'flag' ] && \
-         ! imosh::internal::convert_type \
-             "$(imosh::internal::flag_type "${arg_name}")" \
-             "${arg_value:1}"; then
-        LOG FATAL "the ${arg_name} flag has an invalid value: ${arg_value:1}"
+      if [ "${class_name}" == 'flag' ]; then
+        if ! imosh::internal::convert_type \
+               "$(imosh::internal::flag_type "${arg_name}")" \
+               "${arg_value}" >/dev/null; then
+          LOG FATAL "the ${arg_name} flag has an invalid value: ${arg_value}"
+        else
+          arg_value="$(imosh::internal::convert_type \
+                             "$(imosh::internal::flag_type "${arg_name}")" \
+                             "${arg_value}")"
+        fi
       fi
-      IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=${arg_value:1}")
+      IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=${arg_value}")
       continue
     fi
     LOG FATAL "no such ${class_name} is defined:" \
