Implement the help flag.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -29,107 +29,6 @@ IMOSH_COLOR_MAGENTA="$(imosh::internal::style '0;35')"
 IMOSH_COLOR_CYAN="$(imosh::internal::style '0;36')"
 IMOSH_COLOR_WHITE="$(imosh::internal::style '0;37')"
 
-# __IMOSH_FLAGS_TYPE_<flag name>=<flag type>
-# __IMOSH_FLAGS_DESCRIPTION_<flag name>=<description>
-# __IMOSH_FLAGS_ALIASES=(from:to ...)
-
-imosh::internal::convert_type() {
-  local type="$1"; shift
-  local value="$*"
-
-  case "${type}" in
-    int)
-      if [[ "${value}" =~ ^-?[0-9]+$ ]]; then
-        print "${value}"
-      else
-        return 1
-      fi
-      ;;
-    string)
-      print "${value}"
-      ;;
-    bool)
-      case "${value}" in
-        1|T|t|[Tt]rue) print 1;;
-        0|F|f|[Ff]alse) print 0;;
-        *) return 1;;
-      esac
-      ;;
-    variant)
-      print "${value}"
-      ;;
-    *) LOG FATAL "no such type: ${type}";;
-  esac
-}
-
-imosh::internal::flag_type() {
-  local name="$1"
-
-  if [ "$#" -ne 1 ]; then
-    LOG FATAL 'flag_type requires 1 arugument.'
-  fi
-  eval print '${__IMOSH_FLAGS_TYPE_'"${name}"'}'
-}
-
-imosh::internal::define_flag() {
-  local ARGS_alias
-  eval "${IMOSH_PARSE_ARGUMENTS}"
-  local type="$1"
-  local name="$2"
-  local default_value="$3"
-  local description="$4"
-
-  if [ "$#" -ne 4 ]; then
-    LOG FATAL 'DEFINE_${type} requires 3 arguments.'
-  fi
-  if ! imosh::internal::convert_type \
-           "${type}" "${default_value}" >/dev/null; then
-    LOG FATAL "${type}'s default value should be ${type}: ${default_value}"
-  fi
-  default_value="$(imosh::internal::convert_type "${type}" "${default_value}")"
-  local description="${description} (default: $(
-                         imosh::shell_escape "${default_value}"))"
-  if php::isset "__IMOSH_FLAGS_TYPE_${name}"; then
-    LOG FATAL "already defined flag: ${name}"
-  fi
-  eval "FLAGS_${name}=$(imosh::shell_escape "${default_value}")"
-  eval "__IMOSH_FLAGS_TYPE_${name}=${type}"
-  eval "__IMOSH_FLAGS_DESCRIPTION_${name}=$(
-            imosh::shell_escape "${description}")"
-  if [ "${ARGS_alias}" != '' ]; then
-    imosh::internal::define_flag \
-        "${type}" "${ARGS_alias}" "${default_value}" "${description}"
-    eval "__IMOSH_FLAGS_ALIASES+=( \
-              $(imosh::shell_escape "${name}:${ARGS_alias}"))"
-  fi
-}
-
-DEFINE_string() { imosh::internal::define_flag string "$@"; }
-DEFINE_int() { imosh::internal::define_flag int "$@"; }
-DEFINE_bool() { imosh::internal::define_flag bool "$@"; }
-DEFINE_double() { imosh::internal::define_flag double "$@"; }
-
-imosh::internal::init() {
-  imosh::internal::parse_args flag "$@"
-  if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
-    readonly "${IMOSH_ARGS[@]}"
-  fi
-  if [ "${#__IMOSH_FLAGS_ALIASES[@]}" -ne 0 ]; then
-    for alias in "${__IMOSH_FLAGS_ALIASES[@]}"; do
-      eval "FLAGS_${alias%%:*}=\"\${FLAGS_${alias#*:}}\""
-    done
-  fi
-}
-
-readonly IMOSH_INIT='
-    set -e -u
-    imosh::internal::init "$@"
-    if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
-      set -- "${IMOSH_ARGV[@]}"
-    fi'
-
-__IMOSH_FLAGS_ALIASES=()
-
 imosh::shell_escape() {
   local arg
   local search="'"
@@ -197,6 +96,87 @@ LOG() {
     exit 1
   fi
 }
+
+# Parses arguments without getopt.
+imosh::internal::parse_args() {
+  local class_name="$1"; shift
+
+  local upper_class_name="$(php::strtoupper "${class_name}")"
+  local arg arg_name arg_value
+  IMOSH_ARGV=()
+  IMOSH_ARGS=()
+  while [ "$#" != '0' ]; do
+    local arg="$1"
+    shift
+    if [ "${arg:0:1}" != '-' ]; then
+      IMOSH_ARGV+=("${arg}")
+      continue
+    fi
+    if [ "${arg}" == '--' ]; then
+      IMOSH_ARGV+=("$@")
+      break
+    fi
+    case "${arg}" in
+      --*) arg="${arg:2}";;
+      -*) arg="${arg:1}";;
+    esac
+    arg_name="${arg%%=*}"
+    if [[ ! "${arg_name}" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
+      LOG FATAL "${class_name} name is bad: ${arg_name}"
+    fi
+    arg_value="${arg:${#arg_name}}"
+    if [ "${arg_value:0:1}" != '=' ]; then
+      if [ "${arg_name:0:2}" == 'no' ]; then
+        if php::isset "${upper_class_name}S_${arg_name:2}"; then
+          if [ "${class_name}" == 'flag' ] && \
+             [ "$(imosh::internal::flag_type "${arg_name:2}")" != 'bool' ]; then
+            LOG FATAL "the ${arg_name:2} flag is not a bool flag"
+          fi
+          IMOSH_ARGS+=("${upper_class_name}S_${arg_name:2}=0")
+          continue
+        fi
+      fi
+      if php::isset "${upper_class_name}S_${arg_name}"; then
+        if [ "${class_name}" == 'flag' ] && \
+           [ "$(imosh::internal::flag_type "${arg_name}")" != 'bool' ]; then
+          LOG FATAL "the ${arg_name} flag is not a bool flag"
+        fi
+        IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=1")
+        continue
+      fi
+      LOG FATAL "no such bool ${class_name} is defined:" \
+                "(${upper_class_name}S_)${arg_name}"
+    fi
+    arg_value="${arg_value:1}"
+    if php::isset "${upper_class_name}S_${arg_name}"; then
+      if [ "${class_name}" == 'flag' ]; then
+        if ! imosh::internal::convert_type \
+               "$(imosh::internal::flag_type "${arg_name}")" \
+               "${arg_value}" >/dev/null; then
+          LOG FATAL "the ${arg_name} flag has an invalid value: ${arg_value}"
+        else
+          arg_value="$(imosh::internal::convert_type \
+                             "$(imosh::internal::flag_type "${arg_name}")" \
+                             "${arg_value}")"
+        fi
+      fi
+      IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=${arg_value}")
+      continue
+    fi
+    LOG FATAL "no such ${class_name} is defined:" \
+              "(${upper_class_name}S_)${arg_name}"
+  done
+}
+
+readonly IMOSH_PARSE_ARGUMENTS='
+    local IMOSH_ARGV IMOSH_ARGS
+    imosh::internal::parse_args arg "$@"
+    if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
+      readonly "${IMOSH_ARGS[@]}"
+    fi
+    if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
+      set -- "${IMOSH_ARGV[@]}"
+    fi'
 
 php::array_unique() {
   if [ "$#" -ne 1 ]; then
@@ -399,6 +379,137 @@ imosh::stack_trace() {
   done
 }
 
+# __IMOSH_FLAGS_TYPE_<flag name>=<flag type>
+# __IMOSH_FLAGS_DESCRIPTION_<flag name>=<description>
+# __IMOSH_FLAGS_ALIASES=(from:to ...)
+
+imosh::internal::convert_type() {
+  local type="$1"; shift
+  local value="$*"
+
+  case "${type}" in
+    int)
+      if [[ "${value}" =~ ^-?[0-9]+$ ]]; then
+        print "${value}"
+      else
+        return 1
+      fi
+      ;;
+    string)
+      print "${value}"
+      ;;
+    bool)
+      case "${value}" in
+        1|T|t|[Tt]rue) print 1;;
+        0|F|f|[Ff]alse) print 0;;
+        *) return 1;;
+      esac
+      ;;
+    variant)
+      print "${value}"
+      ;;
+    *) LOG FATAL "no such type: ${type}";;
+  esac
+}
+
+imosh::internal::flag_type() {
+  local name="$1"
+
+  if [ "$#" -ne 1 ]; then
+    LOG FATAL 'flag_type requires 1 arugument.'
+  fi
+  eval print '${__IMOSH_FLAGS_TYPE_'"${name}"'}'
+}
+
+imosh::internal::define_flag() {
+  local ARGS_alias='' ARGS_alias_flag=0
+  eval "${IMOSH_PARSE_ARGUMENTS}"
+  local type="$1"
+  local name="$2"
+  local default_value="$3"
+  local description="$4"
+
+  if [ "$#" -ne 4 ]; then
+    LOG FATAL 'DEFINE_${type} requires 3 arguments.'
+  fi
+  if ! imosh::internal::convert_type \
+           "${type}" "${default_value}" >/dev/null; then
+    LOG FATAL "${type}'s default value should be ${type}: ${default_value}"
+  fi
+  default_value="$(imosh::internal::convert_type "${type}" "${default_value}")"
+  if php::isset "__IMOSH_FLAGS_TYPE_${name}"; then
+    LOG FATAL "already defined flag: ${name}"
+  fi
+  eval "FLAGS_${name}=$(imosh::shell_escape "${default_value}")"
+  eval "__IMOSH_FLAGS_TYPE_${name}=${type}"
+  if [ "${ARGS_alias}" != '' ]; then
+    imosh::internal::define_flag --alias_flag \
+        "${type}" "${ARGS_alias}" "${default_value}" "${description}"
+    eval "__IMOSH_FLAGS_ALIASES+=( \
+              $(imosh::shell_escape "${name}:${ARGS_alias}"))"
+  fi
+  if (( ! ARGS_alias_flag )); then
+    local escaped_default_value=''
+    case "${type}" in
+      int) escaped_default_value="${default_value}";;
+      bool)
+        if (( default_value )); then
+          escaped_default_value='true'
+        else
+          escaped_default_value='false'
+        fi
+        ;;
+      *) escaped_default_value="$(imosh::shell_escape "${default_value}")";;
+    esac
+    description="--${name}=${escaped_default_value}: ${description}"
+    if [ "${ARGS_alias}" != '' ]; then
+      description+=" (Alias: --${ARGS_alias})"
+    fi
+    eval "__IMOSH_FLAGS_DESCRIPTION_${name}=$(
+              imosh::shell_escape "${description}")"
+    __IMOSH_FLAGS+=("${name}")
+  fi
+}
+
+DEFINE_string() { imosh::internal::define_flag string "$@"; }
+DEFINE_int() { imosh::internal::define_flag int "$@"; }
+DEFINE_bool() { imosh::internal::define_flag bool "$@"; }
+DEFINE_double() { imosh::internal::define_flag double "$@"; }
+
+imosh::internal::init() {
+  imosh::internal::parse_args flag "$@"
+  eval "${IMOSH_ARGS[@]}"
+  if [ "${#__IMOSH_FLAGS_ALIASES[@]}" -ne 0 ]; then
+    for alias in "${__IMOSH_FLAGS_ALIASES[@]}"; do
+      eval "FLAGS_${alias%%:*}=\"\${FLAGS_${alias#*:}}\""
+      unset "FLAGS_${alias#*:}"
+    done
+  fi
+  if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
+    readonly "${IMOSH_ARGS[@]}"
+  fi
+  if (( FLAGS_help )); then
+    echo "Usage: ${0} [options ...] [args ...]" >&2
+    echo "Options:" >&2
+    for flag_name in "${__IMOSH_FLAGS[@]}"; do
+      eval "echo \"  \${__IMOSH_FLAGS_DESCRIPTION_${flag_name}}\"" >&2
+    done
+    exit 0
+  fi
+}
+
+readonly IMOSH_INIT='
+    set -e -u
+    imosh::internal::init "$@"
+    if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
+      set -- "${IMOSH_ARGV[@]}"
+    fi'
+
+__IMOSH_FLAGS=()
+__IMOSH_FLAGS_ALIASES=()
+
+DEFINE_bool --alias=h help false 'Print this help message and exit.'
+
 imosh::mktemp() {
   TMPDIR="${TMPDIR%/}"
   export TMPDIR="$(mktemp -d "${TMPDIR:-/tmp}/imosh.XXXXXX")"
@@ -413,84 +524,4 @@ imosh::mktemp() {
 }
 
 imosh::mktemp
-
-# Parses arguments without getopt.
-imosh::internal::parse_args() {
-  local class_name="$1"; shift
-
-  local upper_class_name="$(php::strtoupper "${class_name}")"
-  local arg arg_name arg_value
-  IMOSH_ARGV=()
-  IMOSH_ARGS=()
-  while [ "$#" != '0' ]; do
-    local arg="$1"
-    shift
-    if [ "${arg:0:1}" != '-' ]; then
-      IMOSH_ARGV+=("${arg}")
-      continue
-    fi
-    if [ "${arg}" == '--' ]; then
-      IMOSH_ARGV+=("$@")
-    fi
-    case "${arg}" in
-      --*) arg="${arg:2}";;
-      -*) arg="${arg:1}";;
-    esac
-    arg_name="${arg%%=*}"
-    if [[ ! "${arg_name}" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]]; then
-      LOG FATAL "${class_name} name is bad: ${arg_name}"
-    fi
-    arg_value="${arg:${#arg_name}}"
-    if [ "${arg_value:0:1}" != '=' ]; then
-      if [ "${arg_name:0:2}" == 'no' ]; then
-        if php::isset "${upper_class_name}S_${arg_name:2}"; then
-          if [ "${class_name}" == 'flag' ] && \
-             [ "$(imosh::internal::flag_type "${arg_name:2}")" != 'bool' ]; then
-            LOG FATAL "the ${arg_name:2} flag is not a bool flag"
-          fi
-          IMOSH_ARGS+=("${upper_class_name}S_${arg_name:2}=0")
-          continue
-        fi
-      fi
-      if php::isset "${upper_class_name}S_${arg_name}"; then
-        if [ "${class_name}" == 'flag' ] && \
-           [ "$(imosh::internal::flag_type "${arg_name}")" != 'bool' ]; then
-          LOG FATAL "the ${arg_name} flag is not a bool flag"
-        fi
-        IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=1")
-        continue
-      fi
-      LOG FATAL "no such bool ${class_name} is defined:" \
-                "(${upper_class_name}S_)${arg_name}"
-    fi
-    arg_value="${arg_value:1}"
-    if php::isset "${upper_class_name}S_${arg_name}"; then
-      if [ "${class_name}" == 'flag' ]; then
-        if ! imosh::internal::convert_type \
-               "$(imosh::internal::flag_type "${arg_name}")" \
-               "${arg_value}" >/dev/null; then
-          LOG FATAL "the ${arg_name} flag has an invalid value: ${arg_value}"
-        else
-          arg_value="$(imosh::internal::convert_type \
-                             "$(imosh::internal::flag_type "${arg_name}")" \
-                             "${arg_value}")"
-        fi
-      fi
-      IMOSH_ARGS+=("${upper_class_name}S_${arg_name}=${arg_value}")
-      continue
-    fi
-    LOG FATAL "no such ${class_name} is defined:" \
-              "(${upper_class_name}S_)${arg_name}"
-  done
-}
-
-readonly IMOSH_PARSE_ARGUMENTS='
-    local IMOSH_ARGV IMOSH_ARGS
-    imosh::internal::parse_args arg "$@"
-    if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
-      readonly "${IMOSH_ARGS[@]}"
-    fi
-    if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
-      set -- "${IMOSH_ARGV[@]}"
-    fi'
 
