Change the log format and output log files.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -9,6 +9,31 @@ print() {
   printf "%s" "$*"
 }
 
+__IMOSH_PROGRAM_NAME="${0##*/}"
+__IMOSH_HOSTNAME="$(hostname -s)"
+__IMOSH_USER="${USER}"
+__IMOSH_LOG_PREFIX="${__IMOSH_PROGRAM_NAME}.${__IMOSH_HOSTNAME}.${__IMOSH_USER}"
+__IMOSH_LOG_DIR="${TMPDIR:-/tmp}"
+__IMOSH_LOG_SUFFIX="$(date +'%Y%m%d.%H%M%S').$$"
+
+imosh::internal::log_dir() {
+  local severity="${1}"
+  local path=''
+  path+="${__IMOSH_LOG_DIR}/"
+  path+="${__IMOSH_LOG_PREFIX}.${severity}.${__IMOSH_LOG_SUFFIX}"
+  print "${path}"
+}
+
+if [ -w "${__IMOSH_LOG_DIR}" ]; then
+  exec 101>"$(imosh::internal::log_dir INFO)"
+  exec 102>"$(imosh::internal::log_dir WARNING)"
+  exec 103>"$(imosh::internal::log_dir ERROR)"
+  exec 104>"$(imosh::internal::log_dir FATAL)"
+else
+  exec 101>/dev/null 102>/dev/null 103>/dev/null 104>/dev/null
+  echo "failed to open files to write logs: ${__IMOSH_LOG_DIR}" >&2
+fi
+
 imosh::get_child_processes() {
   local ppid="$1"
   ps -axo ppid,pid | awk "{ if (\$1 == ${ppid}) print \$2; }"
@@ -88,9 +113,32 @@ LOG() {
   local message=(
       "${level:0:1}${datetime}"
       "${pid}"
-      "${BASH_SOURCE[1]}:${BASH_LINENO[0]}]"
+      "${BASH_SOURCE[1]##*/}:${BASH_LINENO[0]}]"
       "$*")
-  echo "${message[@]}" >&2
+  case "${level}" in
+    INFO)
+      echo "${message[*]}" >&2
+      echo "${message[*]}" >&101
+      ;;
+    WARNING)
+      echo "${message[*]}" >&2
+      echo "${message[*]}" >&101
+      echo "${message[*]}" >&102
+      ;;
+    ERROR)
+      echo "${message[*]}" >&2
+      echo "${message[*]}" >&101
+      echo "${message[*]}" >&102
+      echo "${message[*]}" >&103
+      ;;
+    FATAL)
+      echo "${message[*]}" >&2
+      echo "${message[*]}" >&101
+      echo "${message[*]}" >&102
+      echo "${message[*]}" >&103
+      echo "${message[*]}" >&104
+      ;;
+  esac
   if [ "${level}" == 'FATAL' ]; then
     imosh::stack_trace '*** Check failure stack trace: ***'
     exit 1
