Refactoring.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -1,7 +1,7 @@
 #!/bin/bash
 # imos is a utility library for BASH.
 
-IMOSH_VERSION='2014-10-06 00:31:40 +0900 (c1fc443)'
+IMOSH_VERSION='2014-10-06 00:55:54 +0900 (7f5c401)'
 
 # Enables error checking if imosh is called in a script.
 if ! shopt login_shell >/dev/null; then
@@ -17,10 +17,28 @@ fi
 
 # array_map -- Applies a callback to elements.
 #
+# array_map applies a callback to every element.  stream::array_map applies a
+# callback to every line's elements.
+# stream::array_map supports the following functions: array, function, inplace
+# and command.
+#
 # Usage:
 #     void stream::array_map(
 #         string type, string callback [, string arguments...])
 #         < input > output
+#
+# Type:
+# - --array
+#     Reads every line as an array, and applies a callback to every line.
+# - --function
+#     Reads every line as a string and applies a callback.  A callback should be
+#     a function format like: function(string* output, input).
+# - --inplace
+#     Reads every line as a string and applies a callback.  A callback should be
+#     an inplace format like: function(string* input_and_output).
+# - --command
+#     Reads every line as a string and applies a callback.  A callback should be
+#     a command format like: function(string input) > output.
 stream::array_map() {
   if [ "$#" -ge 2 ]; then
     local __array_map_type="$1"; shift
@@ -482,74 +500,75 @@ func::getmypid() {
 
 # func::rand -- Generates a random integer.
 #
-# Usage:
-#   void func::rand(int* variable)
-#   void func::rand(int* variable, int minimum, int maximum)
-#
 # Generates a random integer.
+#
+# Usage:
+#     // a. Function form.
+#     void func::rand(int* variable)
+#     // b. Function form with a range.
+#     void func::rand(int* variable, int minimum, int maximum)
 func::rand() {
-  if [ "$#" -eq 1 ]; then
+  if [ "$#" -eq 3 ]; then
+    local __rand_variable="$1"
+    local __rand_minimum="$2"
+    local __rand_maximum="$3"
+    local __rand_range=0 __rand_value=0
+    if (( __rand_minimum > __rand_maximum )); then
+      LOG FATAL "minimum must be larger than maximum:" \
+                "minimum=${__rand_minimum}, maximum=${__rand_maximum}"
+    fi
+    ((
+      __rand_value = RANDOM ^ (RANDOM << 8) ^
+                     (RANDOM << 16) ^ (RANDOM << 24) ^
+                     (RANDOM << 32) ^ (RANDOM << 40) ^
+                     (RANDOM << 48) ^ (RANDOM << 56),
+      __rand_range = __rand_maximum - __rand_minimum + 1,
+      __rand_value = __rand_minimum +
+          ( __rand_value % __rand_range + __rand_range ) % __rand_range
+    )) || true
+    func::let "${__rand_variable}" "${__rand_value}"
+  elif [ "$#" -eq 1 ]; then
     func::rand "$1" 0 2147483647
     return
-  fi
-  if [ "$#" -ne 3 ]; then
-    LOG FATAL 'func::rand requires one or three arguments.'
-  fi
-
-  local __rand_variable="$1"
-  local __rand_minimum="$2"
-  local __rand_maximum="$3"
-  local __rand_range=0 __rand_value=0
-  if (( __rand_minimum > __rand_maximum )); then
-    LOG FATAL "minimum must be larger than maximum:" \
-              "minimum=${__rand_minimum}, maximum=${__rand_maximum}"
-  fi
-  (( __rand_value = RANDOM ^ (RANDOM << 8) ^
-                    (RANDOM << 16) ^ (RANDOM << 24) ^
-                    (RANDOM << 32) ^ (RANDOM << 40) ^
-                    (RANDOM << 48) ^ (RANDOM << 56),
-     __rand_range = __rand_maximum - __rand_minimum + 1,
-     __rand_value = __rand_minimum +
-         ( __rand_value % __rand_range + __rand_range ) % __rand_range,
-     1 ))
-  func::let "${__rand_variable}" "${__rand_value}"
-}
-
-# func::atexit -- Registers a function on shutdown.
-#
-# Usage:
-#   void func::atexit(string command)
-func::atexit() {
-  if [ "$#" -eq 1 ]; then
-    echo "$1" >>"${__IMOSH_CORE_TMPDIR}/atexit.sh"
   else
     LOG ERROR "Wrong number of arguments: $#"
     return 1
   fi
 }
 
-# func::exit, func::die
+# func::atexit -- Registers a function on shutdown.
+#
+# atexit registers a function to be excuted on shutdown.
 #
 # Usage:
-#   // 1. Message form.
-#   void func::exit(string message)
-#   // 2. Status form.
-#   void func::exit(int status = 0)
-#   // 1. Message form.
-#   void func::die(string message)
-#   // 2. Status form
-#   void func::die(int status = 0)
+#     void func::atexit(string command)
+func::atexit() {
+  if [ "$#" -eq 1 ]; then
+    echo "$1" >> "${__IMOSH_CORE_TMPDIR}/atexit.sh"
+  else
+    LOG ERROR "Wrong number of arguments: $#"
+    return 1
+  fi
+}
+
+# exit, die -- Kills the current script.
 #
 # func::exit kills all the subprocesses of the current program.  If an integer
-# argument is given, func::exit exists with the status.  Otherwise, func::exit
-# shows the given message and exits with status 0.
+# argument is given, func::exit exits with the status.  Otherwise, func::exit
+# shows the given message and exits with status 0.  func::die shows a stack
+# trace and delegates arguments to func::exit.
 #
-# func::die shows a stack trace and delegates arguments to func::exit.
+# Usage:
+#     // 1-a. Function form with a message.
+#     void func::exit(string message)
+#     // 1-b. Function form with a status.
+#     void func::exit(int status = 0)
+#     // 1-c. Function form with a message.
+#     void func::die(string message)
+#     // 1-d. Function form with a status.
+#     void func::die(int status = 0)
 func::exit() {
-  if [ "$#" -eq 0 ]; then
-    set -- 0
-  fi
-  if [ "$#" -le 1 ]; then
+  if [ "$#" -eq 1 ]; then
     local status=0
     if [[ "$1" =~ ^[0-9]+$ ]]; then
       status="$1"
@@ -559,40 +578,48 @@ func::exit() {
       func::println "${message}"
     fi
     imosh::exit "${status}"
+  elif [ "$#" -eq 0 ]; then
+    func::exit 0
   else
-    LOG FATAL "Wrong number of arumnets: $#"
+    LOG ERROR "Wrong number of arguments: $#"
+    return 1
   fi
 }
 
 func::die() {
-  if [ "$#" -le 1 ]; then
-    imosh::stack_trace "*** imosh::die stack trace: ***"
-    func::exit "$@"
-  else
-    LOG ERROR "Wrong number of arguments: $#"
-  fi
+  imosh::stack_trace "*** imosh::die stack trace: ***"
+  func::exit "$@"
 }
 
 # func::throttle -- Throttles by the number of child processes.
 #
+# throttle waits that the number of the child processes is less than a limit.
+# Firstly, throttle waits for 0.1 second, and the n-th retry (n < 10) waits for
+# n * 0.1 seconds.  The n-th retry (n >= 10) waits for 1 second.
+#
 # Usage:
-#   func::throttle(int limit)
+#     void func::throttle(int limit)
 func::throttle() {
-  local __throttle_limit="$1"
-  local __throttle_pids=()
-  local __throttle_sleep=0
+  if [ "$#" -eq 1 ]; then
+    local __throttle_limit="$1"
+    local __throttle_pids=()
+    local __throttle_sleep=0
 
-  while :; do
-    func::getchildpids __throttle_pids
-    if [ "${#__throttle_pids[*]}" -lt "${__throttle_limit}" ]; then
-      break
-    fi
-    if (( __throttle_sleep += 1, __throttle_sleep < 10 )); then
-      sleep "0.${__throttle_sleep}"
-    else
-      sleep 1
-    fi
-  done
+    while :; do
+      func::getchildpids __throttle_pids
+      if [ "${#__throttle_pids[*]}" -lt "${__throttle_limit}" ]; then
+        break
+      fi
+      if (( __throttle_sleep += 1, __throttle_sleep < 10 )); then
+        sleep "0.${__throttle_sleep}"
+      else
+        sleep 1
+      fi
+    done
+  else
+    LOG ERROR "Wrong number of arguments: $#"
+    return 1
+  fi
 }
 
 # func::addslashes -- Quotes a string with backslahses.
