Add func::boolval and func::cast.

diff --git a/imosh b/imosh
--- a/imosh
+++ b/imosh
@@ -660,6 +660,54 @@ func::bin2hex() {
   eval "${__bin2hex_destination}=\"\$(func::print \"${__bin2hex_data}\" | func::bin2hex)\""
 }
 
+# func::boolval -- Casts a variable as a boolean value.
+#
+# Usage:
+#   bool func::boolval(string* variable)
+#
+# Casts variable as a boolean value.  If it fails, returns 1.
+func::boolval() {
+  local __boolval_variable="$1"
+  eval "local __boolval_value=\"\${${__boolval_variable}}\""
+
+  func::trim __boolval_value
+  if [ "${__boolval_value}" = '' ]; then
+    __boolval_value=0
+  elif [[ "${__boolval_value}" =~ ^T|t|[Tt]rue$ ]]; then
+    __boolval_value=1
+  elif [[ "${__boolval_value}" =~ ^F|f|[Ff]alse$ ]]; then
+    __boolval_value=0
+  elif func::intval __boolval_value; then
+    if (( __boolval_value )); then
+      __boolval_value=1
+    fi
+  else
+    func::let "${__boolval_variable}" 0
+    return 1
+  fi
+  func::let "${__boolval_variable}" "${__boolval_value}"
+}
+
+# func::cast -- Casts a variable.
+#
+# Usage:
+#   bool func::cast(variant* variable, string type)
+#
+# Casts variable into a specified type.
+func::cast() {
+  local __cast_variable="$1"
+  local __cast_type="$2"
+
+  case "${__cast_type}" in
+    int)     if ! func::intval "${__cast_variable}"; then return 1; fi;;
+    float)   if ! func::floatval "${__cast_variable}"; then return 1; fi;;
+    string)  if ! func::strval "${__cast_variable}"; then return 1; fi;;
+    bool)    if ! func::boolval "${__cast_variable}"; then return 1; fi;;
+    variant) return 0;;
+    *)       LOG FATAL "Unknown type: ${__cast_type}";;
+  esac
+}
+
 # func::escapeshellarg - Escapes a variable as a shell argument.
 #
 # Usage:
@@ -1305,6 +1353,245 @@ CHECK() {
     IFS=' ' eval 'imosh::stack_trace "*** Check failure: $* ***"'
   fi
 }
+
+# * __IMOSH_FLAGS_TYPE_* has a flag type.
+# * __IMOSH_FLAGS_DESCRIPTION_* has a description.
+# * __IMOSH_FLAGS_ALIASES consists of elements each of which indicates from:to.
+
+# Usage:
+#   void flag_type(type* variable, string flag_name)
+__imosh::flag_type() {
+  if [ "$#" -eq 1 ]; then
+    func::strcpy "$1" "__IMOSH_FLAGS_TYPE_$2"
+  else
+    LOG FATAL "Wrong number of arguments: $#"
+  fi
+}
+
+# Usage:
+#   void __imosh::define_flag(
+#       string type, string name, string default, string description...)
+__imosh::define_flag() {
+  local ARGS_alias='' ARGS_alias_flag=0 ARGS_group='main'
+  eval "${IMOSH_PARSE_ARGUMENTS}"
+  if [ "$#" -lt 4 ]; then
+    LOG FATAL "Wrong number of arguments: $#"
+  fi
+
+  local type="$1" name="$2" default="$3"; shift 3
+  IFS=' ' eval 'local description="$*"'
+
+  func::strtoupper ARGS_group
+  # Change the default value based on its corresponding environment variable.
+  if func::isset "IMOSH_FLAGS_${name}"; then
+    func::strcpy default_value "IMOSH_FLAGS_${name}"
+  fi
+  if ! imosh::internal::convert_type \
+           "${type}" "${default_value}" >/dev/null; then
+    LOG FATAL "${type}'s default value should be ${type}: ${default_value}"
+  fi
+  default_value="$(imosh::internal::convert_type "${type}" "${default_value}")"
+  if func::isset "__IMOSH_FLAGS_TYPE_${name}"; then
+    LOG FATAL "already defined flag: ${name}"
+  fi
+  func::strcpy "FLAGS_${name}" 'default_value'
+  func::strcpy "__IMOSH_FLAGS_TYPE_${name}" 'type'
+  if [ "${ARGS_alias}" != '' ]; then
+    imosh::internal::define_flag "${type}" --alias_flag \
+        "${ARGS_alias}" "${default_value}" "${description}"
+    __IMOSH_FLAGS_ALIASES+=("${name}:${ARGS_alias}")
+  fi
+  if (( ! ARGS_alias_flag )); then
+    local escaped_default_value=''
+    case "${type}" in
+      int) escaped_default_value="${default_value}";;
+      bool)
+        if (( default_value )); then
+          escaped_default_value='true'
+        else
+          escaped_default_value='false'
+        fi
+        ;;
+      *)
+        escaped_default_value="${default_value}"
+        func::escapeshellarg escaped_default_value
+        ;;
+    esac
+    func::let "__IMOSH_FLAGS_DEFAULT_${name}" \
+              "--${name}=${escaped_default_value}"
+    if [ "${ARGS_alias}" != '' ]; then
+      description+=" (Alias: --${ARGS_alias})"
+    fi
+    func::let "__IMOSH_FLAGS_DESCRIPTION_${name}" "${description}"
+    __IMOSH_FLAGS+=("${group}:${name}")
+  fi
+}
+
+# DEFINE_string() { imosh::internal::define_flag string "$@"; }
+# DEFINE_int() { imosh::internal::define_flag int "$@"; }
+# DEFINE_bool() { imosh::internal::define_flag bool "$@"; }
+# DEFINE_double() { imosh::internal::define_flag double "$@"; }
+
+# imosh::internal::get_main_script() {
+#   local depth="${#BASH_SOURCE[@]}"
+#   local main_script="${BASH_SOURCE[$((depth-1))]}"
+#   echo "${main_script}"
+# }
+
+# imosh::internal::get_usage() {
+#   local file="${1}"
+#   grep --max-count=1 -B 1000 -v '^#' "${file}" | grep '^#' | while read line; do
+#     case "${line}" in
+#       '#!'*) continue;;
+#       '# '*) echo "${line:2}";;
+#       '#'*) echo "${line:1}";;
+#     esac
+#   done > "${__IMOSH_CORE_TMPDIR}/usage"
+#   if [ -s "${__IMOSH_CORE_TMPDIR}/usage" ]; then
+#     cat "${__IMOSH_CORE_TMPDIR}/usage"
+#   else
+#     echo 'No description.'
+#   fi
+# }
+
+# imosh::internal::flag_groups() {
+#   local groups=()
+#   local group=''
+#   local main_group_exists=0
+#   local imosh_group_exists=0
+#   for flag_name in "${__IMOSH_FLAGS[@]}"; do
+#     local parts=()
+#     func::explode parts ':' "${flag_name}"
+#     group="${parts[0]}"
+#     local lower_group="${group}"
+#     func::strtolower lower_group
+#     if [ "${lower_group}" == 'main' ]; then
+#       main_group_exists=1
+#     elif [ "${lower_group}" == 'imosh' ]; then
+#       imosh_group_exists=1
+#     else
+#       groups+=("${group}")
+#     fi
+#   done
+#   if (( main_group_exists )); then
+#     echo 'main'
+#   fi
+#   if [ "${#groups[@]}" -ne 0 ]; then
+#     func::array_unique groups
+#     for group in "${groups[@]}"; do
+#       echo "${group}"
+#     done
+#   fi
+#   if (( imosh_group_exists )); then
+#     echo 'imosh'
+#   fi
+# }
+
+# imosh::internal::group_flags() {
+#   local group="$1"
+#   local lower_group="${group}"
+#   func::strtolower lower_group
+
+#   local flags=()
+#   for flag_name in "${__IMOSH_FLAGS[@]}"; do
+#     local parts=()
+#     func::explode parts ':' "${flag_name}"
+#     local lower_part="${parts[0]}"
+#     func::strtolower lower_part
+#     if [ "${lower_group}" != "${lower_part}" ]; then
+#       continue
+#     fi
+#     flags+=("${parts[1]}")
+#   done
+#   func::sort flags
+#   for flag in "${flags[@]}"; do
+#     echo "${flag}"
+#   done
+# }
+
+# imosh::internal::man() {
+#   echo ".TH ${0##*/} 1"; echo
+#   echo '.SH SYNOPSIS'
+#   echo ".B ${0##*/}"; echo '[\fIOPTIONS\fP] [\fIargs...\fP]'; echo
+
+#   echo '.SH DESCRIPTION'
+#   imosh::internal::get_usage "$(imosh::internal::get_main_script)"
+
+#   echo '.SH OPTIONS'
+#   for flag_group in $(imosh::internal::flag_groups); do
+#     local upper_flag_group="${flag_group}"
+#     func::strtoupper upper_flag_group
+#     echo ".SS ${upper_flag_group} OPTIONS"
+#     for flag_name in $(imosh::internal::group_flags "${flag_group}"); do
+#       echo '.TP'
+#       echo -n '\fB'
+#       eval "echo -n \"\${__IMOSH_FLAGS_DEFAULT_${flag_name}}\""
+#       echo '\fP'
+#       eval "echo \"\${__IMOSH_FLAGS_DESCRIPTION_${flag_name}}\""
+#       echo
+#     done
+#   done
+# }
+
+# imosh::internal::help() {
+#   echo "USAGE: ${0##*/} [options...] [args...]"
+#   echo
+#   echo 'DESCRIPTION:'
+#   imosh::internal::get_usage "$(imosh::internal::get_main_script)" | \
+#       while read line; do
+#     echo "  ${line}"
+#   done
+#   echo
+#   echo "OPTIONS:"
+#   for flag_group in $(imosh::internal::flag_groups); do
+#     local upper_flag_group="${flag_group}"
+#     func::strtoupper upper_flag_group
+#     echo "  ${upper_flag_group} OPTIONS:"
+#     for flag_name in $(imosh::internal::group_flags "${flag_group}"); do
+#       eval "echo -n \"    \${__IMOSH_FLAGS_DEFAULT_${flag_name}}:\""
+#       eval "echo \" \${__IMOSH_FLAGS_DESCRIPTION_${flag_name}}\""
+#     done
+#   done
+# }
+
+# imosh::internal::init() {
+#   imosh::internal::parse_args flag "$@"
+#   if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
+#     eval "${IMOSH_ARGS[@]}"
+#   fi
+#   imosh::internal::init_log
+#   if [ "${#__IMOSH_FLAGS_ALIASES[@]}" -ne 0 ]; then
+#     for alias in "${__IMOSH_FLAGS_ALIASES[@]}"; do
+#       eval "FLAGS_${alias%%:*}=\"\${FLAGS_${alias#*:}}\""
+#       unset "FLAGS_${alias#*:}"
+#     done
+#   fi
+#   if [ "${#IMOSH_ARGS[@]}" -ne 0 ]; then
+#     eval "${IMOSH_ARGS[@]}"
+#   fi
+#   if (( FLAGS_help )); then
+#     if [ -t 1 ]; then
+#       local man_file="${__IMOSH_CORE_TMPDIR}/man"
+#       imosh::internal::man >"${man_file}"
+#       man "${man_file}"
+#     elif (( FLAGS_help_groff )); then
+#       imosh::internal::man
+#     else
+#       imosh::internal::help >&2
+#     fi
+#     exit 0
+#   fi
+# }
+
+# readonly IMOSH_INIT='
+#     set -e -u
+#     imosh::internal::init "$@"
+#     if [ "${#IMOSH_ARGV[@]}" -ne 0 ]; then
+#       set -- "${IMOSH_ARGV[@]}"
+#     fi'
+
+# __IMOSH_FLAGS=()
+# __IMOSH_FLAGS_ALIASES=()
 
 # Usage:
 #   imosh::stack_trace [--skip_imosh] [message...]
